config/routes.rb
Rails.application.routes.draw do
  resources :ingredients

  get "recipes/sort_low_high", to: "recipes#sort_low_high", as: "sort_low_high"
  resources :recipes
  
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :allergies, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients

  validates_presence_of :name
  validates :name, uniqueness: true 

  accepts_nested_attributes_for :ingredients 
end

app/models/recipeIngredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy
  has_many :allergies, dependent: :destroy 
  has_many :ingredients, through: :allergies

  # validates :name, uniqueness: true 
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/recipeingredients_controller.rb
class RecipeingredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
    @users = User.all 
    @ingredients = Ingredient.all 
  end

  def create
    @recipe = Recipe.create(name: params[:recipe][:name], user_id: params[:recipe][:user_id])
    recipe_params[:ingredients].each {|i| RecipeIngredient.create(recipe_id: @recipe.id, ingredient_id: i)}
    if @recipe.valid?
      redirect_to @recipe
    else
      flash[:errors] = @recipe.errors.full_messages
      redirect_to new_recipe_path 
    end
  end

  def edit
    @recipe = Recipe.new
    @users = User.all 
    @ingredients = Ingredient.all 
  end

  def update
    @recipe = Recipe.update(recipe_params)
    redirect_to @recipe
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  #custom
  def sort_low_high
    @recipes = Recipe.all.sort_by{|r| r.ingredients.length }
  end

  private

  def set_recipe 
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :user_id, ingredients:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.create(user_params)
  #   if @user.valid?
  #     redirect_to @user
  #   else
  #     flash[:errors] = @user.errors.full_messages
  #     redirect_to new_user_path 
  #   end
  # end

  # def edit
  # end

  # def update
  #   @user = User.update(user_params)
  #   redirect_to @user
  # end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user 
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipeingredients_helper.rb
module RecipeingredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minirecipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<% if flash[:errors] %>
  <%= flash[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<h3>
<%= form_with model:@recipe do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.collection_select :user_id, @users, :id, :name %>

  <%= f.collection_check_boxes :ingredients, @ingredients, :id, :name, include_hidden: false %>
  <%= f.submit %>
<% end %>
</h3>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<% @recipes.each do |r| %>
  <p>
  <%= link_to r.name, r %>
  </p>
<% end %>

<%= button_to "Sort by Number of Ingredients", sort_low_high_path, method: :get %>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<ol>
<% @recipe.ingredients.each do |i|%>
  <li><%= i.name %></li>
<% end %>
</ol>

<%= button_to "Edit", edit_recipe_path, method: :get %>
<%= button_to "Delete this recipe", @recipe, method: :delete %>
<%= link_to "Back to all recipes", recipes_path %>

app/views/recipes/sort_low_high.html.erb
<% @recipes.each do |r| %>
  <p>
  <%= r.name %> <b>|</b> <%= r.ingredients.count %>
  </p>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div>
  <%= link_to user.name, user %>
  </div>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<br>
<ul>
<% @user.recipes.each do |recipe| %>
  <li><%= link_to recipe.name, recipe %></li>
<% end %>
</ul>
<br>
<div>
<%= button_to "Delete user", @user, method: :delete %>
</div>